version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_prices
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - app_network
    command: [ "postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf" ]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./db/pgadmin_servers.json:/pgadmin4/servers.json
      - ./.pgpass:/pgpassfile
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network

  backend:
    build: ./back-end
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: car_prices
      DATABASE_PORT: '5432'
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
